# Fuentes permitidas (v1) — Eugenia valida.
# Formato: name, url, type (official|media), feed (rss|sitemap), feed_url

- name: "Diario Río Uruguay"
  type: media
  url: "https://www.diarioriouruguay.com/"
  feed: sitemap
  feed_url: "https://www.diarioriouruguay.com/sitemap.xml"

- name: "Diario Junio"
  type: media
  url: "https://www.diariojunio.com.ar/"
  feed: rss
  feed_url: "https://www.diariojunio.com.ar/feed/"

- name: "El Entre Ríos"
  type: media
  url: "https://www.elentrerios.com/"
  feed: sitemap
  feed_url: "https://www.elentrerios.com/sitemap.xml"

- name: "Municipalidad de Concordia"
  type: official
  url: "https://www.concordia.gob.ar/"
  feed: rss
  feed_url: "https://www.concordia.gob.ar/rss.xml"

# Falta: Concejo Deliberante (pasanos link de comunicados/prensa para sumarlo)

- name: "El Heraldo"
  type: media
  url: "https://www.elheraldo.com.ar/"
  feed: sitemap
  feed_url: "https://www.elheraldo.com.ar/sitemap.xml"

- name: "Diario El Sol"
  type: media
  url: "https://diarioelsol.com.ar/"
  feed: sitemap
  feed_url: "https://diarioelsol.com.ar/sitemap.xml"

- name: "Concordia24"
  type: media
  url: "https://concordia24.com.ar/"
  feed: rss
  feed_url: "https://concordia24.com.ar/feed/"
