# Fuentes permitidas (v1) — Eugenia valida.
# Formato: name, url, rss (si aplica), type (official|media)

- name: "Diario Río Uruguay"
  type: media
  url: "https://www.diarioriouruguay.com.ar/"
  rss: ""

- name: "Diario Junio"
  type: media
  url: "https://www.diariojunio.com.ar/"
  rss: ""

- name: "El Entre Ríos"
  type: media
  url: "https://www.elentrerios.com/"
  rss: ""

# TODO: agregar oficiales (Municipalidad, Concejo, Gobierno ER) con URLs/RSS.
